version: "3.9"

services:
  front:
    image: node:14.20.1-alpine
    working_dir: /usr/app/front
    command: "yarn install && yarn run build"

  server:
    image: node:14.20.1-alpine
    working_dir: /usr/app/server
    command: "yarn install && yarn run build"
